/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.9.dev1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ru.tmin10.EVESecurityService.serverApi.api;

import ru.tmin10.EVESecurityService.serverApi.invoker.ApiException;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdAgentsResearch200Ok;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdAgentsResearchForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdAgentsResearchInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdBlueprints200Ok;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdBlueprintsForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdBlueprintsInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdChatChannels200Ok;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdChatChannelsForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdChatChannelsInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdCorporationhistory200Ok;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdCorporationhistoryInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdMedals200Ok;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdMedalsForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdMedalsInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdOk;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdPortraitInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdPortraitNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdPortraitOk;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdRolesForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdRolesInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdStandings200Ok;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdStandingsForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdStandingsInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersNames200Ok;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersNamesInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.PostCharactersAffiliation200Ok;
import ru.tmin10.EVESecurityService.serverApi.model.PostCharactersAffiliationInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.PostCharactersAffiliationUnprocessableEntity;
import ru.tmin10.EVESecurityService.serverApi.model.PostCharactersCharacterIdCspaCharacters;
import ru.tmin10.EVESecurityService.serverApi.model.PostCharactersCharacterIdCspaCreated;
import ru.tmin10.EVESecurityService.serverApi.model.PostCharactersCharacterIdCspaForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.PostCharactersCharacterIdCspaInternalServerError;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CharacterApi
 */
@Ignore
public class CharacterApiTest {

    private final CharacterApi api = new CharacterApi();

    
    /**
     * Get character&#39;s public information
     *
     * Public information about a character  ---  Alternate route: &#x60;/v4/characters/{character_id}/&#x60;  Alternate route: &#x60;/dev/characters/{character_id}/&#x60;   ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        GetCharactersCharacterIdOk response = api.getCharactersCharacterId(characterId, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get agents research
     *
     * Return a list of agents research information for a character. The formula for finding the current research points with an agent is: currentPoints &#x3D; remainderPoints + pointsPerDay * days(currentTime - researchStartDate)  ---  Alternate route: &#x60;/v1/characters/{character_id}/agents_research/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/agents_research/&#x60;  Alternate route: &#x60;/dev/characters/{character_id}/agents_research/&#x60;   ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdAgentsResearchTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCharactersCharacterIdAgentsResearch200Ok> response = api.getCharactersCharacterIdAgentsResearch(characterId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get blueprints
     *
     * Return a list of blueprints the character has  ---  Alternate route: &#x60;/v1/characters/{character_id}/blueprints/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/blueprints/&#x60;  Alternate route: &#x60;/dev/characters/{character_id}/blueprints/&#x60;   ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdBlueprintsTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCharactersCharacterIdBlueprints200Ok> response = api.getCharactersCharacterIdBlueprints(characterId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get chat channels
     *
     * Return chat channels that a character is the owner or an operator of  ---  Alternate route: &#x60;/v1/characters/{character_id}/chat_channels/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/chat_channels/&#x60;  Alternate route: &#x60;/dev/characters/{character_id}/chat_channels/&#x60;   ---  This route is cached for up to 300 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdChatChannelsTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCharactersCharacterIdChatChannels200Ok> response = api.getCharactersCharacterIdChatChannels(characterId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation history
     *
     * Get a list of all the corporations a character has been a member of  ---  Alternate route: &#x60;/v1/characters/{character_id}/corporationhistory/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/corporationhistory/&#x60;  Alternate route: &#x60;/dev/characters/{character_id}/corporationhistory/&#x60;   ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdCorporationhistoryTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCharactersCharacterIdCorporationhistory200Ok> response = api.getCharactersCharacterIdCorporationhistory(characterId, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get medals
     *
     * Return a list of medals the character has  ---  Alternate route: &#x60;/v1/characters/{character_id}/medals/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/medals/&#x60;  Alternate route: &#x60;/dev/characters/{character_id}/medals/&#x60;   ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdMedalsTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCharactersCharacterIdMedals200Ok> response = api.getCharactersCharacterIdMedals(characterId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get character portraits
     *
     * Get portrait urls for a character  ---  Alternate route: &#x60;/v2/characters/{character_id}/portrait/&#x60;  Alternate route: &#x60;/dev/characters/{character_id}/portrait/&#x60;   ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdPortraitTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        GetCharactersCharacterIdPortraitOk response = api.getCharactersCharacterIdPortrait(characterId, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get character corporation roles
     *
     * Returns a character&#39;s corporation roles  ---  Alternate route: &#x60;/v1/characters/{character_id}/roles/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/roles/&#x60;  Alternate route: &#x60;/dev/characters/{character_id}/roles/&#x60;   ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdRolesTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<String> response = api.getCharactersCharacterIdRoles(characterId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get standings
     *
     * Return character standings from agents, NPC corporations, and factions  ---  Alternate route: &#x60;/v1/characters/{character_id}/standings/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/standings/&#x60;  Alternate route: &#x60;/dev/characters/{character_id}/standings/&#x60;   ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdStandingsTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCharactersCharacterIdStandings200Ok> response = api.getCharactersCharacterIdStandings(characterId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get character names
     *
     * Resolve a set of character IDs to character names  ---  Alternate route: &#x60;/v1/characters/names/&#x60;  Alternate route: &#x60;/legacy/characters/names/&#x60;  Alternate route: &#x60;/dev/characters/names/&#x60;   ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersNamesTest() throws ApiException {
        List<Long> characterIds = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCharactersNames200Ok> response = api.getCharactersNames(characterIds, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Character affiliation
     *
     * Bulk lookup of character IDs to corporation, alliance and faction  ---  Alternate route: &#x60;/v1/characters/affiliation/&#x60;  Alternate route: &#x60;/legacy/characters/affiliation/&#x60;  Alternate route: &#x60;/dev/characters/affiliation/&#x60;   ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postCharactersAffiliationTest() throws ApiException {
        List<Integer> characters = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<PostCharactersAffiliation200Ok> response = api.postCharactersAffiliation(characters, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Calculate a CSPA charge cost
     *
     * Takes a source character ID in the url and a set of target character ID&#39;s in the body, returns a CSPA charge cost  ---  Alternate route: &#x60;/v3/characters/{character_id}/cspa/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/cspa/&#x60;  Alternate route: &#x60;/dev/characters/{character_id}/cspa/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postCharactersCharacterIdCspaTest() throws ApiException {
        Integer characterId = null;
        PostCharactersCharacterIdCspaCharacters characters = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        PostCharactersCharacterIdCspaCreated response = api.postCharactersCharacterIdCspa(characterId, characters, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
}
