/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.9.dev1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ru.tmin10.EVESecurityService.serverApi.api;

import ru.tmin10.EVESecurityService.serverApi.invoker.ApiException;
import ru.tmin10.EVESecurityService.serverApi.model.DeleteFleetsFleetIdMembersMemberIdForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.DeleteFleetsFleetIdMembersMemberIdInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.DeleteFleetsFleetIdMembersMemberIdNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.DeleteFleetsFleetIdSquadsSquadIdForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.DeleteFleetsFleetIdSquadsSquadIdInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.DeleteFleetsFleetIdSquadsSquadIdNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.DeleteFleetsFleetIdWingsWingIdForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.DeleteFleetsFleetIdWingsWingIdInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.DeleteFleetsFleetIdWingsWingIdNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.GetFleetsFleetIdForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.GetFleetsFleetIdInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetFleetsFleetIdMembers200Ok;
import ru.tmin10.EVESecurityService.serverApi.model.GetFleetsFleetIdMembersForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.GetFleetsFleetIdMembersInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetFleetsFleetIdMembersNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.GetFleetsFleetIdNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.GetFleetsFleetIdOk;
import ru.tmin10.EVESecurityService.serverApi.model.GetFleetsFleetIdWings200Ok;
import ru.tmin10.EVESecurityService.serverApi.model.GetFleetsFleetIdWingsForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.GetFleetsFleetIdWingsInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetFleetsFleetIdWingsNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.PostFleetsFleetIdMembersForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.PostFleetsFleetIdMembersInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.PostFleetsFleetIdMembersInvitation;
import ru.tmin10.EVESecurityService.serverApi.model.PostFleetsFleetIdMembersNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.PostFleetsFleetIdMembersUnprocessableEntity;
import ru.tmin10.EVESecurityService.serverApi.model.PostFleetsFleetIdWingsCreated;
import ru.tmin10.EVESecurityService.serverApi.model.PostFleetsFleetIdWingsForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.PostFleetsFleetIdWingsInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.PostFleetsFleetIdWingsNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.PostFleetsFleetIdWingsWingIdSquadsCreated;
import ru.tmin10.EVESecurityService.serverApi.model.PostFleetsFleetIdWingsWingIdSquadsForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.PostFleetsFleetIdWingsWingIdSquadsInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.PostFleetsFleetIdWingsWingIdSquadsNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.PutFleetsFleetIdBadRequest;
import ru.tmin10.EVESecurityService.serverApi.model.PutFleetsFleetIdForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.PutFleetsFleetIdInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.PutFleetsFleetIdMembersMemberIdForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.PutFleetsFleetIdMembersMemberIdInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.PutFleetsFleetIdMembersMemberIdMovement;
import ru.tmin10.EVESecurityService.serverApi.model.PutFleetsFleetIdMembersMemberIdNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.PutFleetsFleetIdMembersMemberIdUnprocessableEntity;
import ru.tmin10.EVESecurityService.serverApi.model.PutFleetsFleetIdNewSettings;
import ru.tmin10.EVESecurityService.serverApi.model.PutFleetsFleetIdNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.PutFleetsFleetIdSquadsSquadIdForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.PutFleetsFleetIdSquadsSquadIdInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.PutFleetsFleetIdSquadsSquadIdNaming;
import ru.tmin10.EVESecurityService.serverApi.model.PutFleetsFleetIdSquadsSquadIdNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.PutFleetsFleetIdWingsWingIdForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.PutFleetsFleetIdWingsWingIdInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.PutFleetsFleetIdWingsWingIdNaming;
import ru.tmin10.EVESecurityService.serverApi.model.PutFleetsFleetIdWingsWingIdNotFound;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FleetsApi
 */
@Ignore
public class FleetsApiTest {

    private final FleetsApi api = new FleetsApi();

    
    /**
     * Kick fleet member
     *
     * Kick a fleet member  ---  Alternate route: &#x60;/v1/fleets/{fleet_id}/members/{member_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/members/{member_id}/&#x60;  Alternate route: &#x60;/dev/fleets/{fleet_id}/members/{member_id}/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteFleetsFleetIdMembersMemberIdTest() throws ApiException {
        Long fleetId = null;
        Integer memberId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        api.deleteFleetsFleetIdMembersMemberId(fleetId, memberId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Delete fleet squad
     *
     * Delete a fleet squad, only empty squads can be deleted  ---  Alternate route: &#x60;/v1/fleets/{fleet_id}/squads/{squad_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/squads/{squad_id}/&#x60;  Alternate route: &#x60;/dev/fleets/{fleet_id}/squads/{squad_id}/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteFleetsFleetIdSquadsSquadIdTest() throws ApiException {
        Long fleetId = null;
        Long squadId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        api.deleteFleetsFleetIdSquadsSquadId(fleetId, squadId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Delete fleet wing
     *
     * Delete a fleet wing, only empty wings can be deleted. The wing may contain squads, but the squads must be empty  ---  Alternate route: &#x60;/v1/fleets/{fleet_id}/wings/{wing_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/wings/{wing_id}/&#x60;  Alternate route: &#x60;/dev/fleets/{fleet_id}/wings/{wing_id}/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteFleetsFleetIdWingsWingIdTest() throws ApiException {
        Long fleetId = null;
        Long wingId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        api.deleteFleetsFleetIdWingsWingId(fleetId, wingId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get fleet information
     *
     * Return details about a fleet  ---  Alternate route: &#x60;/v1/fleets/{fleet_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/&#x60;  Alternate route: &#x60;/dev/fleets/{fleet_id}/&#x60;   ---  This route is cached for up to 5 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFleetsFleetIdTest() throws ApiException {
        Long fleetId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        GetFleetsFleetIdOk response = api.getFleetsFleetId(fleetId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get fleet members
     *
     * Return information about fleet members  ---  Alternate route: &#x60;/v1/fleets/{fleet_id}/members/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/members/&#x60;  Alternate route: &#x60;/dev/fleets/{fleet_id}/members/&#x60;   ---  This route is cached for up to 5 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFleetsFleetIdMembersTest() throws ApiException {
        Long fleetId = null;
        String datasource = null;
        String language = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetFleetsFleetIdMembers200Ok> response = api.getFleetsFleetIdMembers(fleetId, datasource, language, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get fleet wings
     *
     * Return information about wings in a fleet  ---  Alternate route: &#x60;/v1/fleets/{fleet_id}/wings/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/wings/&#x60;  Alternate route: &#x60;/dev/fleets/{fleet_id}/wings/&#x60;   ---  This route is cached for up to 5 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFleetsFleetIdWingsTest() throws ApiException {
        Long fleetId = null;
        String datasource = null;
        String language = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetFleetsFleetIdWings200Ok> response = api.getFleetsFleetIdWings(fleetId, datasource, language, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Create fleet invitation
     *
     * Invite a character into the fleet, if a character has a CSPA charge set, it is not possible to invite them to the fleet using ESI  ---  Alternate route: &#x60;/v1/fleets/{fleet_id}/members/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/members/&#x60;  Alternate route: &#x60;/dev/fleets/{fleet_id}/members/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postFleetsFleetIdMembersTest() throws ApiException {
        Long fleetId = null;
        PostFleetsFleetIdMembersInvitation invitation = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        api.postFleetsFleetIdMembers(fleetId, invitation, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Create fleet wing
     *
     * Create a new wing in a fleet  ---  Alternate route: &#x60;/v1/fleets/{fleet_id}/wings/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/wings/&#x60;  Alternate route: &#x60;/dev/fleets/{fleet_id}/wings/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postFleetsFleetIdWingsTest() throws ApiException {
        Long fleetId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        PostFleetsFleetIdWingsCreated response = api.postFleetsFleetIdWings(fleetId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Create fleet squad
     *
     * Create a new squad in a fleet  ---  Alternate route: &#x60;/v1/fleets/{fleet_id}/wings/{wing_id}/squads/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/wings/{wing_id}/squads/&#x60;  Alternate route: &#x60;/dev/fleets/{fleet_id}/wings/{wing_id}/squads/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postFleetsFleetIdWingsWingIdSquadsTest() throws ApiException {
        Long fleetId = null;
        Long wingId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        PostFleetsFleetIdWingsWingIdSquadsCreated response = api.postFleetsFleetIdWingsWingIdSquads(fleetId, wingId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Update fleet
     *
     * Update settings about a fleet  ---  Alternate route: &#x60;/v1/fleets/{fleet_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/&#x60;  Alternate route: &#x60;/dev/fleets/{fleet_id}/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putFleetsFleetIdTest() throws ApiException {
        Long fleetId = null;
        PutFleetsFleetIdNewSettings newSettings = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        api.putFleetsFleetId(fleetId, newSettings, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Move fleet member
     *
     * Move a fleet member around  ---  Alternate route: &#x60;/v1/fleets/{fleet_id}/members/{member_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/members/{member_id}/&#x60;  Alternate route: &#x60;/dev/fleets/{fleet_id}/members/{member_id}/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putFleetsFleetIdMembersMemberIdTest() throws ApiException {
        Long fleetId = null;
        Integer memberId = null;
        PutFleetsFleetIdMembersMemberIdMovement movement = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        api.putFleetsFleetIdMembersMemberId(fleetId, memberId, movement, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Rename fleet squad
     *
     * Rename a fleet squad  ---  Alternate route: &#x60;/v1/fleets/{fleet_id}/squads/{squad_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/squads/{squad_id}/&#x60;  Alternate route: &#x60;/dev/fleets/{fleet_id}/squads/{squad_id}/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putFleetsFleetIdSquadsSquadIdTest() throws ApiException {
        Long fleetId = null;
        PutFleetsFleetIdSquadsSquadIdNaming naming = null;
        Long squadId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        api.putFleetsFleetIdSquadsSquadId(fleetId, naming, squadId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Rename fleet wing
     *
     * Rename a fleet wing  ---  Alternate route: &#x60;/v1/fleets/{fleet_id}/wings/{wing_id}/&#x60;  Alternate route: &#x60;/legacy/fleets/{fleet_id}/wings/{wing_id}/&#x60;  Alternate route: &#x60;/dev/fleets/{fleet_id}/wings/{wing_id}/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putFleetsFleetIdWingsWingIdTest() throws ApiException {
        Long fleetId = null;
        PutFleetsFleetIdWingsWingIdNaming naming = null;
        Long wingId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        api.putFleetsFleetIdWingsWingId(fleetId, naming, wingId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
}
