/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.9.dev1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ru.tmin10.EVESecurityService.serverApi.api;

import ru.tmin10.EVESecurityService.serverApi.invoker.ApiException;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdKillmailsRecent200Ok;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdKillmailsRecentForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdKillmailsRecentInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetKillmailsKillmailIdKillmailHashInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetKillmailsKillmailIdKillmailHashOk;
import ru.tmin10.EVESecurityService.serverApi.model.GetKillmailsKillmailIdKillmailHashUnprocessableEntity;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for KillmailsApi
 */
@Ignore
public class KillmailsApiTest {

    private final KillmailsApi api = new KillmailsApi();

    
    /**
     * List kills and losses
     *
     * Return a list of character&#39;s recent kills and losses  ---  Alternate route: &#x60;/v1/characters/{character_id}/killmails/recent/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/killmails/recent/&#x60;  Alternate route: &#x60;/dev/characters/{character_id}/killmails/recent/&#x60;   ---  This route is cached for up to 120 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdKillmailsRecentTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        Integer maxCount = null;
        Integer maxKillId = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCharactersCharacterIdKillmailsRecent200Ok> response = api.getCharactersCharacterIdKillmailsRecent(characterId, datasource, maxCount, maxKillId, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get a single killmail
     *
     * Return a single killmail from its ID and hash  ---  Alternate route: &#x60;/v1/killmails/{killmail_id}/{killmail_hash}/&#x60;  Alternate route: &#x60;/legacy/killmails/{killmail_id}/{killmail_hash}/&#x60;  Alternate route: &#x60;/dev/killmails/{killmail_id}/{killmail_hash}/&#x60;   ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getKillmailsKillmailIdKillmailHashTest() throws ApiException {
        String killmailHash = null;
        Integer killmailId = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        GetKillmailsKillmailIdKillmailHashOk response = api.getKillmailsKillmailIdKillmailHash(killmailHash, killmailId, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
}
