/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.9.dev1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ru.tmin10.EVESecurityService.serverApi.api;

import ru.tmin10.EVESecurityService.serverApi.invoker.ApiException;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseBloodlines200Ok;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseBloodlinesInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseCategoriesCategoryIdInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseCategoriesCategoryIdNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseCategoriesCategoryIdOk;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseCategoriesInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseConstellationsConstellationIdInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseConstellationsConstellationIdNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseConstellationsConstellationIdOk;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseConstellationsInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseFactions200Ok;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseFactionsInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseGraphicsGraphicIdInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseGraphicsGraphicIdNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseGraphicsGraphicIdOk;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseGraphicsInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseGroupsGroupIdInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseGroupsGroupIdNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseGroupsGroupIdOk;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseGroupsInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseMoonsMoonIdInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseMoonsMoonIdNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseMoonsMoonIdOk;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniversePlanetsPlanetIdInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniversePlanetsPlanetIdNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniversePlanetsPlanetIdOk;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseRaces200Ok;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseRacesInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseRegionsInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseRegionsRegionIdInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseRegionsRegionIdNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseRegionsRegionIdOk;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseStargatesStargateIdInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseStargatesStargateIdNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseStargatesStargateIdOk;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseStationsStationIdInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseStationsStationIdNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseStationsStationIdOk;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseStructuresInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseStructuresStructureIdForbidden;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseStructuresStructureIdInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseStructuresStructureIdNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseStructuresStructureIdOk;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseSystemJumps200Ok;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseSystemJumpsInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseSystemKills200Ok;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseSystemKillsInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseSystemsInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseSystemsSystemIdInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseSystemsSystemIdNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseSystemsSystemIdOk;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseTypesInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseTypesTypeIdInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseTypesTypeIdNotFound;
import ru.tmin10.EVESecurityService.serverApi.model.GetUniverseTypesTypeIdOk;
import ru.tmin10.EVESecurityService.serverApi.model.PostUniverseNames200Ok;
import ru.tmin10.EVESecurityService.serverApi.model.PostUniverseNamesInternalServerError;
import ru.tmin10.EVESecurityService.serverApi.model.PostUniverseNamesNotFound;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UniverseApi
 */
@Ignore
public class UniverseApiTest {

    private final UniverseApi api = new UniverseApi();

    
    /**
     * Get bloodlines
     *
     * Get a list of bloodlines  ---  Alternate route: &#x60;/v1/universe/bloodlines/&#x60;  Alternate route: &#x60;/legacy/universe/bloodlines/&#x60;  Alternate route: &#x60;/dev/universe/bloodlines/&#x60;   ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseBloodlinesTest() throws ApiException {
        String datasource = null;
        String language = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetUniverseBloodlines200Ok> response = api.getUniverseBloodlines(datasource, language, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get item categories
     *
     * Get a list of item categories  ---  Alternate route: &#x60;/v1/universe/categories/&#x60;  Alternate route: &#x60;/legacy/universe/categories/&#x60;  Alternate route: &#x60;/dev/universe/categories/&#x60;   ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseCategoriesTest() throws ApiException {
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<Integer> response = api.getUniverseCategories(datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get item category information
     *
     * Get information of an item category  ---  Alternate route: &#x60;/v1/universe/categories/{category_id}/&#x60;  Alternate route: &#x60;/legacy/universe/categories/{category_id}/&#x60;  Alternate route: &#x60;/dev/universe/categories/{category_id}/&#x60;   ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseCategoriesCategoryIdTest() throws ApiException {
        Integer categoryId = null;
        String datasource = null;
        String language = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseCategoriesCategoryIdOk response = api.getUniverseCategoriesCategoryId(categoryId, datasource, language, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get constellations
     *
     * Get a list of constellations  ---  Alternate route: &#x60;/v1/universe/constellations/&#x60;  Alternate route: &#x60;/legacy/universe/constellations/&#x60;  Alternate route: &#x60;/dev/universe/constellations/&#x60;   ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseConstellationsTest() throws ApiException {
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<Integer> response = api.getUniverseConstellations(datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get constellation information
     *
     * Get information on a constellation  ---  Alternate route: &#x60;/v1/universe/constellations/{constellation_id}/&#x60;  Alternate route: &#x60;/legacy/universe/constellations/{constellation_id}/&#x60;  Alternate route: &#x60;/dev/universe/constellations/{constellation_id}/&#x60;   ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseConstellationsConstellationIdTest() throws ApiException {
        Integer constellationId = null;
        String datasource = null;
        String language = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseConstellationsConstellationIdOk response = api.getUniverseConstellationsConstellationId(constellationId, datasource, language, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get factions
     *
     * Get a list of factions  ---  Alternate route: &#x60;/v1/universe/factions/&#x60;  Alternate route: &#x60;/legacy/universe/factions/&#x60;  Alternate route: &#x60;/dev/universe/factions/&#x60;   ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseFactionsTest() throws ApiException {
        String datasource = null;
        String language = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetUniverseFactions200Ok> response = api.getUniverseFactions(datasource, language, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get graphics
     *
     * Get a list of graphics  ---  Alternate route: &#x60;/v1/universe/graphics/&#x60;  Alternate route: &#x60;/legacy/universe/graphics/&#x60;  Alternate route: &#x60;/dev/universe/graphics/&#x60;   ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseGraphicsTest() throws ApiException {
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<Integer> response = api.getUniverseGraphics(datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get graphic information
     *
     * Get information on a graphic  ---  Alternate route: &#x60;/v1/universe/graphics/{graphic_id}/&#x60;  Alternate route: &#x60;/legacy/universe/graphics/{graphic_id}/&#x60;  Alternate route: &#x60;/dev/universe/graphics/{graphic_id}/&#x60;   ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseGraphicsGraphicIdTest() throws ApiException {
        Integer graphicId = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseGraphicsGraphicIdOk response = api.getUniverseGraphicsGraphicId(graphicId, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get item groups
     *
     * Get a list of item groups  ---  Alternate route: &#x60;/v1/universe/groups/&#x60;  Alternate route: &#x60;/legacy/universe/groups/&#x60;  Alternate route: &#x60;/dev/universe/groups/&#x60;   ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseGroupsTest() throws ApiException {
        String datasource = null;
        Integer page = null;
        String userAgent = null;
        String xUserAgent = null;
        List<Integer> response = api.getUniverseGroups(datasource, page, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get item group information
     *
     * Get information on an item group  ---  Alternate route: &#x60;/v1/universe/groups/{group_id}/&#x60;  Alternate route: &#x60;/legacy/universe/groups/{group_id}/&#x60;  Alternate route: &#x60;/dev/universe/groups/{group_id}/&#x60;   ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseGroupsGroupIdTest() throws ApiException {
        Integer groupId = null;
        String datasource = null;
        String language = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseGroupsGroupIdOk response = api.getUniverseGroupsGroupId(groupId, datasource, language, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get moon information
     *
     * Get information on a moon  ---  Alternate route: &#x60;/v1/universe/moons/{moon_id}/&#x60;  Alternate route: &#x60;/legacy/universe/moons/{moon_id}/&#x60;  Alternate route: &#x60;/dev/universe/moons/{moon_id}/&#x60;   ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseMoonsMoonIdTest() throws ApiException {
        Integer moonId = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseMoonsMoonIdOk response = api.getUniverseMoonsMoonId(moonId, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get planet information
     *
     * Get information on a planet  ---  Alternate route: &#x60;/v1/universe/planets/{planet_id}/&#x60;  Alternate route: &#x60;/legacy/universe/planets/{planet_id}/&#x60;  Alternate route: &#x60;/dev/universe/planets/{planet_id}/&#x60;   ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniversePlanetsPlanetIdTest() throws ApiException {
        Integer planetId = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniversePlanetsPlanetIdOk response = api.getUniversePlanetsPlanetId(planetId, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get character races
     *
     * Get a list of character races  ---  Alternate route: &#x60;/v1/universe/races/&#x60;  Alternate route: &#x60;/legacy/universe/races/&#x60;  Alternate route: &#x60;/dev/universe/races/&#x60;   ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseRacesTest() throws ApiException {
        String datasource = null;
        String language = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetUniverseRaces200Ok> response = api.getUniverseRaces(datasource, language, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get regions
     *
     * Get a list of regions  ---  Alternate route: &#x60;/v1/universe/regions/&#x60;  Alternate route: &#x60;/legacy/universe/regions/&#x60;  Alternate route: &#x60;/dev/universe/regions/&#x60;   ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseRegionsTest() throws ApiException {
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<Integer> response = api.getUniverseRegions(datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get region information
     *
     * Get information on a region  ---  Alternate route: &#x60;/v1/universe/regions/{region_id}/&#x60;  Alternate route: &#x60;/legacy/universe/regions/{region_id}/&#x60;  Alternate route: &#x60;/dev/universe/regions/{region_id}/&#x60;   ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseRegionsRegionIdTest() throws ApiException {
        Integer regionId = null;
        String datasource = null;
        String language = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseRegionsRegionIdOk response = api.getUniverseRegionsRegionId(regionId, datasource, language, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get stargate information
     *
     * Get information on a stargate  ---  Alternate route: &#x60;/v1/universe/stargates/{stargate_id}/&#x60;  Alternate route: &#x60;/legacy/universe/stargates/{stargate_id}/&#x60;  Alternate route: &#x60;/dev/universe/stargates/{stargate_id}/&#x60;   ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseStargatesStargateIdTest() throws ApiException {
        Integer stargateId = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseStargatesStargateIdOk response = api.getUniverseStargatesStargateId(stargateId, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get station information
     *
     * Get information on a station  ---  Alternate route: &#x60;/v2/universe/stations/{station_id}/&#x60;  Alternate route: &#x60;/dev/universe/stations/{station_id}/&#x60;   ---  This route is cached for up to 300 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseStationsStationIdTest() throws ApiException {
        Integer stationId = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseStationsStationIdOk response = api.getUniverseStationsStationId(stationId, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * List all public structures
     *
     * List all public structures  ---  Alternate route: &#x60;/v1/universe/structures/&#x60;  Alternate route: &#x60;/legacy/universe/structures/&#x60;  Alternate route: &#x60;/dev/universe/structures/&#x60;   ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseStructuresTest() throws ApiException {
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<Long> response = api.getUniverseStructures(datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get structure information
     *
     * Returns information on requested structure, if you are on the ACL. Otherwise, returns \&quot;Forbidden\&quot; for all inputs.  ---  Alternate route: &#x60;/v1/universe/structures/{structure_id}/&#x60;  Alternate route: &#x60;/legacy/universe/structures/{structure_id}/&#x60;  Alternate route: &#x60;/dev/universe/structures/{structure_id}/&#x60;   ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseStructuresStructureIdTest() throws ApiException {
        Long structureId = null;
        String datasource = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseStructuresStructureIdOk response = api.getUniverseStructuresStructureId(structureId, datasource, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get system jumps
     *
     * Get the number of jumps in solar systems within the last hour, excluding wormhole space. Only systems with jumps will be listed  ---  Alternate route: &#x60;/v1/universe/system_jumps/&#x60;  Alternate route: &#x60;/legacy/universe/system_jumps/&#x60;  Alternate route: &#x60;/dev/universe/system_jumps/&#x60;   ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseSystemJumpsTest() throws ApiException {
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetUniverseSystemJumps200Ok> response = api.getUniverseSystemJumps(datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get system kills
     *
     * Get the number of ship, pod and NPC kills per solar system within the last hour, excluding wormhole space. Only systems with kills will be listed  ---  Alternate route: &#x60;/v1/universe/system_kills/&#x60;  Alternate route: &#x60;/legacy/universe/system_kills/&#x60;  Alternate route: &#x60;/dev/universe/system_kills/&#x60;   ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseSystemKillsTest() throws ApiException {
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetUniverseSystemKills200Ok> response = api.getUniverseSystemKills(datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get solar systems
     *
     * Get a list of solar systems  ---  Alternate route: &#x60;/v1/universe/systems/&#x60;  Alternate route: &#x60;/legacy/universe/systems/&#x60;  Alternate route: &#x60;/dev/universe/systems/&#x60;   ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseSystemsTest() throws ApiException {
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<Integer> response = api.getUniverseSystems(datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get solar system information
     *
     * Get information on a solar system  ---  Alternate route: &#x60;/v2/universe/systems/{system_id}/&#x60;  Alternate route: &#x60;/dev/universe/systems/{system_id}/&#x60;   ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseSystemsSystemIdTest() throws ApiException {
        Integer systemId = null;
        String datasource = null;
        String language = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseSystemsSystemIdOk response = api.getUniverseSystemsSystemId(systemId, datasource, language, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get types
     *
     * Get a list of type ids  ---  Alternate route: &#x60;/v1/universe/types/&#x60;  Alternate route: &#x60;/legacy/universe/types/&#x60;  Alternate route: &#x60;/dev/universe/types/&#x60;   ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseTypesTest() throws ApiException {
        String datasource = null;
        Integer page = null;
        String userAgent = null;
        String xUserAgent = null;
        List<Integer> response = api.getUniverseTypes(datasource, page, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get type information
     *
     * Get information on a type  ---  Alternate route: &#x60;/v2/universe/types/{type_id}/&#x60;   ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUniverseTypesTypeIdTest() throws ApiException {
        Integer typeId = null;
        String datasource = null;
        String language = null;
        String userAgent = null;
        String xUserAgent = null;
        GetUniverseTypesTypeIdOk response = api.getUniverseTypesTypeId(typeId, datasource, language, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get names and categories for a set of ID&#39;s
     *
     * Resolve a set of IDs to names and categories. Supported ID&#39;s for resolving are: Characters, Corporations, Alliances, Stations, Solar Systems, Constellations, Regions, Types.  ---  Alternate route: &#x60;/v2/universe/names/&#x60;  Alternate route: &#x60;/dev/universe/names/&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postUniverseNamesTest() throws ApiException {
        List<Integer> ids = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<PostUniverseNames200Ok> response = api.postUniverseNames(ids, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
}
