/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.9.dev1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 200 ok object
 */
export interface GetAlliancesAllianceIdOk {
    /**
     * the full name of the alliance
     */
    allianceName: string;

    /**
     * date_founded string
     */
    dateFounded: Date;

    /**
     * the executor corporation ID, if this alliance is not closed
     */
    executorCorp?: number;

    /**
     * the short name of the alliance
     */
    ticker: string;

}
