/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.9.dev1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * head object
 */
export interface GetCharactersCharacterIdPlanetsPlanetIdHead {
    /**
     * head_id integer
     */
    headId: number;

    /**
     * latitude number
     */
    latitude: number;

    /**
     * longitude number
     */
    longitude: number;

}
