/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.9.dev1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * pin object
 */
export interface GetCharactersCharacterIdPlanetsPlanetIdPin {
    /**
     * expiry_time string
     */
    expiryTime?: Date;

    extractorDetails?: models.GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails;

    factoryDetails?: models.GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails;

    /**
     * install_time string
     */
    installTime?: Date;

    /**
     * last_cycle_start string
     */
    lastCycleStart?: Date;

    /**
     * latitude number
     */
    latitude: number;

    /**
     * longitude number
     */
    longitude: number;

    /**
     * pin_id integer
     */
    pinId: number;

    /**
     * schematic_id integer
     */
    schematicId?: number;

    /**
     * type_id integer
     */
    typeId: number;

}
