/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.9.dev1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 200 ok object
 */
export interface GetCharactersCharacterIdChatChannels200Ok {
    /**
     * allowed array
     */
    allowed: Array<models.GetCharactersCharacterIdChatChannelsAllowed>;

    /**
     * blocked array
     */
    blocked: Array<models.GetCharactersCharacterIdChatChannelsBlocked>;

    /**
     * Unique channel ID. Always negative for player-created channels. Permanent (CCP created) channels have a positive ID, but don't appear in the API
     */
    channelId: number;

    /**
     * Normalized, unique string used to compare channel names
     */
    comparisonKey: string;

    /**
     * Whether this is a password protected channel
     */
    hasPassword: boolean;

    /**
     * Message of the day for this channel
     */
    motd: string;

    /**
     * muted array
     */
    muted: Array<models.GetCharactersCharacterIdChatChannelsMuted>;

    /**
     * Displayed name of channel
     */
    name: string;

    /**
     * operators array
     */
    operators: Array<models.GetCharactersCharacterIdChatChannelsOperator>;

    /**
     * owner_id integer
     */
    ownerId: number;

}
