/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.9.dev1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * muted object
 */
export interface GetCharactersCharacterIdChatChannelsMuted {
    /**
     * ID of a muted channel member
     */
    accessorId: number;

    /**
     * accessor_type string
     */
    accessorType: GetCharactersCharacterIdChatChannelsMuted.AccessorTypeEnum;

    /**
     * Time at which this accessor will no longer be muted
     */
    endAt?: Date;

    /**
     * Reason this accessor is muted
     */
    reason?: string;

}
export namespace GetCharactersCharacterIdChatChannelsMuted {
    export enum AccessorTypeEnum {
        Character = <any> 'character',
        Corporation = <any> 'corporation',
        Alliance = <any> 'alliance'
    }
}
