/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.9.dev1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 200 ok object
 */
export interface GetCorporationsCorporationIdStructures200Ok {
    /**
     * ID of the corporation that owns the structure
     */
    corporationId: number;

    /**
     * This week's vulnerability windows, Monday is day 0
     */
    currentVul: Array<models.GetCorporationsCorporationIdStructuresCurrentVul>;

    /**
     * Date on which the structure will run out of fuel
     */
    fuelExpires?: Date;

    /**
     * Next week's vulnerability windows, Monday is day 0
     */
    nextVul: Array<models.GetCorporationsCorporationIdStructuresNextVul>;

    /**
     * The id of the ACL profile for this citadel
     */
    profileId: number;

    /**
     * Contains a list of service upgrades, and their state
     */
    services?: Array<models.GetCorporationsCorporationIdStructuresService>;

    /**
     * Date at which the structure will move to it's next state
     */
    stateTimerEnd?: Date;

    /**
     * Date at which the structure entered it's current state
     */
    stateTimerStart?: Date;

    /**
     * The Item ID of the structure
     */
    structureId: number;

    /**
     * The solar system the structure is in
     */
    systemId: number;

    /**
     * The type id of the structure
     */
    typeId: number;

    /**
     * Date at which the structure will unanchor
     */
    unanchorsAt?: Date;

}
