/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.9.dev1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * operator object
 */
export interface GetCharactersCharacterIdChatChannelsOperator {
    /**
     * ID of a channel operator
     */
    accessorId: number;

    /**
     * accessor_type string
     */
    accessorType: GetCharactersCharacterIdChatChannelsOperator.AccessorTypeEnum;

}
export namespace GetCharactersCharacterIdChatChannelsOperator {
    export enum AccessorTypeEnum {
        Character = <any> 'character',
        Corporation = <any> 'corporation',
        Alliance = <any> 'alliance'
    }
}
