/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.9.dev1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * skill object
 */
export interface GetCharactersCharacterIdSkillsSkill {
    /**
     * current_skill_level integer
     */
    currentSkillLevel?: number;

    /**
     * skill_id integer
     */
    skillId?: number;

    /**
     * skillpoints_in_skill integer
     */
    skillpointsInSkill?: number;

}
