/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.9.dev1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * recipient object
 */
export interface GetCharactersCharacterIdMailRecipient {
    /**
     * recipient_id integer
     */
    recipientId: number;

    /**
     * recipient_type string
     */
    recipientType: GetCharactersCharacterIdMailRecipient.RecipientTypeEnum;

}
export namespace GetCharactersCharacterIdMailRecipient {
    export enum RecipientTypeEnum {
        Alliance = <any> 'alliance',
        Character = <any> 'character',
        Corporation = <any> 'corporation',
        MailingList = <any> 'mailing_list'
    }
}
