/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.9.dev1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * modifier object
 */
export interface GetDogmaEffectsEffectIdModifier {
    /**
     * domain string
     */
    domain: string;

    /**
     * func string
     */
    func: string;

    /**
     * modified_attribute_id integer
     */
    modifiedAttributeId: number;

    /**
     * modifying_attribute_id integer
     */
    modifyingAttributeId: number;

    /**
     * operator integer
     */
    operator: number;

}
