/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.9.dev1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * victim object
 */
export interface GetKillmailsKillmailIdKillmailHashVictim {
    /**
     * alliance_id integer
     */
    allianceId?: number;

    /**
     * character_id integer
     */
    characterId?: number;

    /**
     * corporation_id integer
     */
    corporationId?: number;

    /**
     * How much total damage was taken by the victim 
     */
    damageTaken: number;

    /**
     * faction_id integer
     */
    factionId?: number;

    /**
     * items array
     */
    items?: Array<models.GetKillmailsKillmailIdKillmailHashItem1>;

    position?: models.GetKillmailsKillmailIdKillmailHashPosition;

    /**
     * The ship that the victim was piloting and was destroyed 
     */
    shipTypeId: number;

}
