/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.9.dev1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * item object
 */
export interface GetKillmailsKillmailIdKillmailHashItem {
    /**
     * flag integer
     */
    flag: number;

    /**
     * item_type_id integer
     */
    itemTypeId: number;

    /**
     * quantity_destroyed integer
     */
    quantityDestroyed?: number;

    /**
     * quantity_dropped integer
     */
    quantityDropped?: number;

    /**
     * singleton integer
     */
    singleton: number;

}
