/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.9.dev1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 200 ok object
 */
export interface GetUniverseSystemsSystemIdOk {
    /**
     * The constellation this solar system is in
     */
    constellationId: number;

    /**
     * name string
     */
    name: string;

    /**
     * planets array
     */
    planets: Array<models.GetUniverseSystemsSystemIdPlanet>;

    position?: models.GetUniverseSystemsSystemIdPosition;

    /**
     * security_class string
     */
    securityClass?: string;

    /**
     * security_status number
     */
    securityStatus: number;

    /**
     * stargates array
     */
    stargates: Array<number>;

    /**
     * system_id integer
     */
    systemId: number;

}
