/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.9.dev1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 200 ok object
 */
export interface GetUniverseTypesTypeIdOk {
    /**
     * capacity number
     */
    capacity?: number;

    /**
     * description string
     */
    description: string;

    /**
     * dogma_attributes array
     */
    dogmaAttributes?: Array<models.GetUniverseTypesTypeIdDogmaAttribute>;

    /**
     * dogma_effects array
     */
    dogmaEffects?: Array<models.GetUniverseTypesTypeIdDogmaEffect>;

    /**
     * graphic_id integer
     */
    graphicId?: number;

    /**
     * group_id integer
     */
    groupId: number;

    /**
     * icon_id integer
     */
    iconId?: number;

    /**
     * mass number
     */
    mass?: number;

    /**
     * name string
     */
    name: string;

    /**
     * portion_size integer
     */
    portionSize?: number;

    /**
     * published boolean
     */
    published: boolean;

    /**
     * radius number
     */
    radius?: number;

    /**
     * type_id integer
     */
    typeId: number;

    /**
     * volume number
     */
    volume?: number;

}
