/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.9.dev1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ru.tmin10.EVESecurityService.serverApi.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdBookmarksCoordinates;
import ru.tmin10.EVESecurityService.serverApi.model.GetCharactersCharacterIdBookmarksItem;

/**
 * target object
 */
@ApiModel(description = "target object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-11T18:18:08.749+04:00")
public class GetCharactersCharacterIdBookmarksTarget {
  @SerializedName("coordinates")
  private GetCharactersCharacterIdBookmarksCoordinates coordinates = null;

  @SerializedName("item")
  private GetCharactersCharacterIdBookmarksItem item = null;

  @SerializedName("location_id")
  private Long locationId = null;

  public GetCharactersCharacterIdBookmarksTarget coordinates(GetCharactersCharacterIdBookmarksCoordinates coordinates) {
    this.coordinates = coordinates;
    return this;
  }

   /**
   * Get coordinates
   * @return coordinates
  **/
  @ApiModelProperty(example = "null", value = "")
  public GetCharactersCharacterIdBookmarksCoordinates getCoordinates() {
    return coordinates;
  }

  public void setCoordinates(GetCharactersCharacterIdBookmarksCoordinates coordinates) {
    this.coordinates = coordinates;
  }

  public GetCharactersCharacterIdBookmarksTarget item(GetCharactersCharacterIdBookmarksItem item) {
    this.item = item;
    return this;
  }

   /**
   * Get item
   * @return item
  **/
  @ApiModelProperty(example = "null", value = "")
  public GetCharactersCharacterIdBookmarksItem getItem() {
    return item;
  }

  public void setItem(GetCharactersCharacterIdBookmarksItem item) {
    this.item = item;
  }

  public GetCharactersCharacterIdBookmarksTarget locationId(Long locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * location_id integer
   * @return locationId
  **/
  @ApiModelProperty(example = "null", required = true, value = "location_id integer")
  public Long getLocationId() {
    return locationId;
  }

  public void setLocationId(Long locationId) {
    this.locationId = locationId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCharactersCharacterIdBookmarksTarget getCharactersCharacterIdBookmarksTarget = (GetCharactersCharacterIdBookmarksTarget) o;
    return Objects.equals(this.coordinates, getCharactersCharacterIdBookmarksTarget.coordinates) &&
        Objects.equals(this.item, getCharactersCharacterIdBookmarksTarget.item) &&
        Objects.equals(this.locationId, getCharactersCharacterIdBookmarksTarget.locationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(coordinates, item, locationId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCharactersCharacterIdBookmarksTarget {\n");
    
    sb.append("    coordinates: ").append(toIndentedString(coordinates)).append("\n");
    sb.append("    item: ").append(toIndentedString(item)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

